version: "3"

services:
  postgres:
    container_name: database_backup
    image: postgres:14.2
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54321:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
      - ../migration/init:/docker-entrypoint-initdb.d